from . import res_partner
from . import purchase_order
from . import project_task_type
from . import project_task
from . import stock_picking
from . import project_project
from . import sale_order
from . import res_config_settings
from . import product_order_line