{
    'name': 'MultisafePay',
    'version': '18.0.1.0.0',
    'license': "LGPL-3",
    'category': 'Sales/pos',
    'sequence': 1,
    'summary': 'Payment Provider',
    'description': "Payment Provider by SIDHARTH P",
    'author': "ASMI",
    'data': [
        'views/payment_multisafepay_template.xml',
        'views/payment_provider_views.xml',
        'data/payment_method_data.xml',
        'data/payment_provider_data.xml',
    ],
    'depends': ['payment'],
    'application': True,
    'auto_install': True,
    'installable': True,
    'post_init_hook': 'post_init_hook',
    'uninstall_hook': 'uninstall_hook',
}
